config/routes.rb
Rails.application.routes.draw do

  
  
  devise_for :users
  root to: "forum_threads#index"
    get 'forum_threads/autocomplete_forum_thread_title'
      resources :forum_threads do
          put :pinit, on: :member
          resources :forum_posts
      end

end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
	belongs_to :user
	belongs_to :forum_thread

	validates :content, presence: true
end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
	extend FriendlyId

	friendly_id :title, use: :slugged
	belongs_to :user
	# tambah depent destroy ketika thread di hapus maka post ikut terhapus
	has_many :forum_posts, dependent: :destroy

	validates :title, presence: true, length:{maximum: 50}
	validates :content, presence: true



	def sticky
		sticky_order !=100
	end

	def pinit!
		self.sticky_order = 1
		self.save
	end

	scope :title_search, -> (title) {where("title like ?", title)}
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :forum_threads
  has_many :forum_posts
  
  enum level: [:member, :admin]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :set_forum_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create]
  # GET /forum_posts
  # GET /forum_posts.json
  def index
    @forum_posts = ForumPost.all
  end

  # GET /forum_posts/1
  # GET /forum_posts/1.json
  def show
  end

  # GET /forum_posts/new
  def new

    @forum_post = ForumPost.new
  end

  # GET /forum_posts/1/edit
  def edit
  end

  # POST /forum_posts
  # POST /forum_posts.json
  def create
    @thread = ForumThread.friendly.find(params[:forum_thread_id])
    @post = ForumPost.new(forum_post_params)
 
    @post.forum_thread = @thread
    # menggunakan current user
    @post.user = current_user

    if @post.save
      redirect_to forum_thread_path(@thread)
    else
      render 'forum_threads/show'
    end

    

    

    # respond_to do |format|
    #   if @forum_post.save
    #     format.html { redirect_to @forum_post, notice: 'Forum post was successfully created.' }
    #     format.json { render :show, status: :created, location: @forum_post }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @forum_post.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /forum_posts/1
  # PATCH/PUT /forum_posts/1.json
  def update
    respond_to do |format|
      if @forum_post.update(forum_post_params)
        format.html { redirect_to @forum_post, notice: 'Forum post was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_post }
      else
        format.html { render :edit }
        format.json { render json: @forum_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_posts/1
  # DELETE /forum_posts/1.json
  def destroy
    @forum_post.destroy
    respond_to do |format|
      format.html { redirect_to forum_posts_url, notice: 'Forum post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_post
      @forum_post = ForumPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_post_params
      params.require(:forum_post).permit(:content, :forum_thread_id, :user_id)
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :set_forum_thread, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :create]
 
 #untuk search
 autocomplete :ForumThread, :title, :full => true
  # GET /forum_threads
  # GET /forum_threads.json
  def index
    
    if params[:search]
      @forum_threads = ForumThread.title_search("%#{params[:search]}%").order(sticky_order: :asc).order(id: :desc).paginate(per_page: 3,page: params[:page])
    else
      @forum_threads = ForumThread.order(sticky_order: :asc).order(id: :desc).paginate(per_page: 3,page: params[:page])
    end  
  end

  # GET /forum_threads/1
  # GET /forum_threads/1.json
  def show
    @thread = ForumThread.friendly.find(params[:id])
    @post = ForumPost.new
    @posts = @thread.forum_posts.paginate(per_page: 2, page: params[:page])
  end

  # GET /forum_threads/new
  def new
    @forum_thread = ForumThread.new
    @post = ForumPost.new

  end

  # GET /forum_threads/1/edit
  def edit

    @thread = ForumThread.friendly.find(params[:id])
    # authorize akan mencari ForumThreadPolicy bagian edit
    authorize @thread
  end

  # POST /forum_threads
  # POST /forum_threads.json
  def create
    @forum_thread = ForumThread.new(forum_thread_params)
    # menggunakan current user
    @forum_thread.user = current_user
    respond_to do |format|
      if @forum_thread.save
        format.html { redirect_to @forum_thread, notice: 'Forum thread was successfully created.' }
        format.json { render :show, status: :created, location: @forum_thread }
      else
        
        format.html { render :new }
        format.json { render json: @forum_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum_threads/1
  # PATCH/PUT /forum_threads/1.json
  def update
    respond_to do |format|
      if @forum_thread.update(forum_thread_params)
        format.html { redirect_to @forum_thread, notice: 'Forum thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_thread }
      else
        format.html { render :edit }
        format.json { render json: @forum_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum_threads/1
  # DELETE /forum_threads/1.json
  def destroy
    @forum_thread = ForumThread.friendly.find(params[:id])
    authorize @forum_thread

    @forum_thread.destroy

    redirect_to root_path, notice:'Forum thread was successfully destroyed.'
    # respond_to do |format|
    #   format.html { redirect_to forum_threads_url, notice: 'Forum thread was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end


# pinit
  def pinit
      # find params id terlebih dahulu
      @thread = ForumThread.friendly.find(params[:id])
      @thread.pinit!

      redirect_to root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_thread
      @forum_thread = ForumThread.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_thread_params
      params.require(:forum_thread).permit(:title, :content, :sticky_order, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/forum_posts/_form.html.erb
<%= form_for(@forum_post) do |f| %>
  <% if @forum_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_post.errors.count, "error") %> prohibited this forum_post from being saved:</h2>

      <ul>
      <% @forum_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :forum_thread_id %><br>
    <%= f.number_field :forum_thread_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_posts/edit.html.erb
<h1>Editing Forum Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_post %> |
<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forum Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Forum thread</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forum_posts.each do |forum_post| %>
      <tr>
        <td><%= forum_post.content %></td>
        <td><%= forum_post.forum_thread_id %></td>
        <td><%= forum_post.user_id %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/forum_posts/new.html.erb
<h1>New Forum Post</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_posts_path %>

app/views/forum_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @forum_post.content %>
</p>

<p>
  <strong>Forum thread:</strong>
  <%= @forum_post.forum_thread_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @forum_post.user_id %>
</p>

<%= link_to 'Edit', edit_forum_post_path(@forum_post) %> |
<%= link_to 'Back', forum_posts_path %>

app/views/forum_threads/_form.html.erb
    <%= form_for(@forum_thread) do |f| %>
  <% if @forum_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
      <% @forum_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class:'form-control', rows:10 %>
  </div>

  <div class="form-group">
    <%= f.submit 'submit', class:'form-control btn btn-primary' %>
  </div>
<% end %>    

app/views/forum_threads/edit.html.erb
<div class="row">
 	<div class="col-md-6 col-md-offset-3">
 		<h1>Editing Forum Thread</h1>

		<%= render 'form' %>
 	</div>	
</div>


<%= link_to 'Show', @forum_thread %> |
<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p id="notice" >
    <%= notice %>
      
    </p>

      <% if user_signed_in? %>

      <%= link_to 'New Forum thread', new_forum_thread_path, class:'btn btn-primary' %>
      <% end %>
      <!-- looping -->
      <% @forum_threads.each do |thread| %>
        <div class="thread">
          <h3><%= link_to thread.title.titleize, forum_thread_path(thread) %> 
          <!-- sticky order jika != 100, function nya ada di model forumthread -->
          <% if thread.sticky %>
            <span class="glyphicon glyphicon-pushpin"></span>
          <% end %>
          </h3>
          <div class="date">
            <%= thread.created_at rescue '' %> oleh <%= thread.user.name rescue '' %>
          </div>
          <div class="content">
            <%= truncate thread.content, length: 200 %>
          </div> 
          <div class="comment">
            <%= thread.forum_posts.count %> comment
          </div> 

          <div class="action">
            
            <%= link_to 'pin it', pinit_forum_thread_path(thread), method: :put %>
          </div>
        <div style="clear: both;"></div>
        </div>
      <% end %>

      <%= will_paginate @forum_threads,renderer: BootstrapPagination::Rails %>

  </div>
  
</div>

app/views/forum_threads/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	
	<%= render 'form' %>
	</div>
	
</div>




<!-- <%#= render 'form' %> -->


<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	<!-- menampilkan error comment -->


		<div class="thread">
		<h3> <%= @thread.title.titleize %></h3>
		<div class="date">
			<%= @thread.created_at %> oleh <%= @thread.user.name %>
		</div>
		<div class="content">
			<%= @thread.content %>
		</div>

		<!-- link edit ditampilkan untuk thread yang sesuai user login, selain itu tidak -->
		<!-- dengan menggunakan policy -->
		<% if policy(@thread).edit? %>
			<%= link_to 'edit', edit_forum_thread_path(@thread), class:'edit' %>
			<!-- untuk link edit -->
			 |<span>
				<%= link_to 'delete', forum_thread_path(@thread), method: :delete, data: {confirm: 'are you sure want to delete?'} %>	
			</span>
			

		<% end %>
		<div style="clear: both;"></div>	
		</div>

<!-- untuk paginate post -->
		<% if @thread.forum_posts.any? %>
			<% @posts.each do |post| %>
				<div class="thread">
					<div class="date">
						<%= post.created_at %> oleh <%= post.user.name %>
					</div>
					<div class="content">
						<%= post.content %>
					</div>
				</div>

			<% end %>
			<% else %>
				<div>
					jadilah yang pertama comment
				</div>
		<% end %>
		<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
		<% if @post.errors.any? %>
			<div class="alert alert-danger alert-dismissible">
			 <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<% @post.errors.full_messages.each do |error| %>
					<span><%= error %></span><br>
				<% end %>
			</div>
		<% end %>

		<!-- nested resource -->
	<% if user_signed_in? %>
		<%= form_for [@thread, @post] do |f| %>
			<div class='form-group'>
				<%= f.label 'Comment' %>	
				<%= f.text_area :content,rows: 5, class:'form-control' %>	
			</div>
			<div class="form-group">
				<%= f.submit 'Submit',class: 'btn btn-primary form-control' %>
			</div>
			
		<% end %>
	<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to 'MiniApp2', root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

      <!-- untuk search -->
      <%= form_tag(root_path, :method => "get", id:"search-form", class:"navbar-form navbar-left") do %>

          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder:"search", data:{autocomplete: forum_threads_autocomplete_forum_thread_title_path}, class:'form-control' %>

            <%= submit_tag 'Search',class:"btn btn-default" %>
          </div>

        
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <!-- memunculkan nama user yang login dengan current_user -->

          <%= user_signed_in? ? current_user.name : 'Halo guest' %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!-- <li><a href="#">Daftar</a></li> -->

            <!-- menambahkan apakah user sudah login, dgn method dari devise user_signed_in?  -->

            <% if user_signed_in? %>
              <!-- jika user sudah sign_in maka muncul tombol logout -->
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

                <% else %>
                  <li><%= link_to 'Daftar', new_user_registration_path %></li>
                  <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
            
            <!-- <li><a href="#">Login</a></li> -->
            
            <!-- <li><a href="#">Logout</a></li> -->
            
            
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miniapp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container">

<!-- untuk alert -->


	<%= yield %>	
</div>


</body>
</html>